version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    volumes:
      - ./elastic:/usr/share/elasticsearch/data
    environment:
      - node.name=elastic_node01
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elk  
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.9.2
  #   volumes:
  #   - ./logstash/config:/config-dir
  #   - ./logstash/data:/logstash
  #   links:
  #   - elasticsearch
  #   command: logstash -f /config-dir/logstash.conf
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch
  #   links:
  #     - elasticsearch

networks:
  elk:
    driver: bridge